+ another tests

diff --git a/pcc-tests/regress/misc/Makefile b/pcc-tests/regress/misc/Makefile
--- a/pcc-tests/regress/misc/Makefile
+++ b/pcc-tests/regress/misc/Makefile
@@ -7,6 +7,7 @@ CC=pcc
 CFLAGS= 
 LDFLAGS=
 LOG=misc.log
+MAKE=make
 
 REGRESS_TARGETS = arith001 arith002 
 
@@ -27,6 +28,17 @@ test:
 		${CC} ${CFLAGS} -o $$TARGET2.out $$TARGET2.c 2>/dev/null && \
 			echo "failed" || echo "passed" ;\
 	done 
+	@cd shlib && ${MAKE} clean 
+	@printf  "   %-20s \t\t " "shlib1" ;
+	@cd shlib && ${MAKE} combined_check 2>/dev/null && \
+			echo "passed" || echo "failed" ;
+	@printf  "   %-20s \t\t " "shlib2" ;
+	@cd shlib && ${MAKE} static_check 2>/dev/null && \
+			echo "passed" || echo "failed" ;
+	@printf  "   %-20s \t\t " "shlib3" ;
+	@cd shlib && ${MAKE} shared_check 2>/dev/null && \
+			echo "passed" || echo "failed" ;
+
 
 
 page:
@@ -47,11 +59,25 @@ page:
 			printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ${LOG} || \
 			printf "<td align=\"center\" bgcolor=\"green\"> %s </td></tr>\n" "passed" >> ${LOG}  ;\
 	done
+	@cd shlib && ${MAKE} clean 
+	@printf  "<tr><td bgcolor=\"#dcdcdc\"> %s </td>" "shlib1" >> ${LOG} ; 
+	@cd shlib && ${MAKE} combined_check 1>/dev/null 2>/dev/null && \
+			printf "<td align=\"center\" bgcolor=\"green\" > %s </td></tr>\n" "passed" >> ../${LOG} || \
+			printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ../${LOG} ;
+	@printf  "<tr><td bgcolor=\"#dcdcdc\"> %s </td>" "shlib2" >> ${LOG} ;
+	@cd shlib && ${MAKE} static_check 1>/dev/null 2>/dev/null && \
+			printf "<td align=\"center\" bgcolor=\"green\" > %s </td></tr>\n" "passed" >> ../${LOG} || \
+			printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ../${LOG} ;
+	@printf  "<tr><td bgcolor=\"#dcdcdc\"> %s </td>" "shlib3" >> ${LOG} ;
+	@cd shlib && ${MAKE} shared_check 1>/dev/null 2>/dev/null && \
+			printf "<td align=\"center\" bgcolor=\"green\" > %s </td></tr>\n" "passed" >> ../${LOG} || \
+			printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ../${LOG} ;
 	@printf "</table>\n" >> ${LOG}
 
 
 
 clean:
+	cd shlib && ${MAKE} clean 
 	/bin/rm -rf *.out 
 	/bin/rm -rf *.core
 	/bin/rm -rf ${LOG}
