several tests from jira bug tracker

diff --git a/pcc-tests/regress/jira/Makefile b/pcc-tests/regress/jira/Makefile
--- a/pcc-tests/regress/jira/Makefile
+++ b/pcc-tests/regress/jira/Makefile
@@ -8,9 +8,14 @@ CFLAGS=
 LDFLAGS=
 LOG=jira.log
 
-REGRESS_TARGETS = 
+REGRESS_TARGETS = PCC-21 PCC-23 PCC-45 PCC-47 PCC-57 \
+						PCC-62 PCC-63 PCC-65 PCC-68 PCC-69 PCC-77 \
+						PCC-84 PCC-85 PCC-97 PCC-101 PCC-123 PCC-125 \
+						PCC-129 PCC-131 PCC-135 PCC-138 PCC-149 PCC-152 \
+						PCC-154 PCC-155 PCC-157 PCC-158 \
+						PCC-160
 
-REGRESS_TARGETS_FAIL = 
+REGRESS_TARGETS_FAIL = PCC-33
 
 test:  
 	@echo " Running tests from jira bug tracker : "  
@@ -27,6 +32,12 @@ test:
 		${CC} ${CFLAGS} -o $$TARGET2.out $$TARGET2.c 2>/dev/null && \
 			echo "failed" || echo "passed" ;\
 	done 
+	@printf  "   %-20s \t\t " "PCC-70" ;
+	@${CC} ${CFLAGS} -o PCC-70.out -c PCC-70.c 2>/dev/null && \
+		echo "passed" || echo "failed" ;
+	@printf  "   %-20s \t\t " "PCC-159" ;
+	@${CC} ${CFLAGS} -o PCC-159 -c PCC-159.c 2>/dev/null && \
+		echo "passed" || echo "failed" ;
 
 
 page:
@@ -47,6 +58,14 @@ page:
 			printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ${LOG} || \
 			printf "<td align=\"center\" bgcolor=\"green\"> %s </td></tr>\n" "passed" >> ${LOG} ;\
 	done
+	@printf  "<tr><td bgcolor=\"#dcdcdc\"> %s </td>" " PCC-70 " >> ${LOG} ;
+	@${CC} ${CFLAGS} -o PCC-70.out -c PCC-70.c 2>/dev/null && \
+		printf "<td align=\"center\" bgcolor=\"green\" > %s </td></tr>\n" "passed" >> ${LOG} || \
+		printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ${LOG} ;
+	@printf  "<tr><td bgcolor=\"#dcdcdc\"> %s </td>" " PCC-159 " >> ${LOG} ;
+	@${CC} ${CFLAGS} -o PCC-159.out -c PCC-159.c 2>/dev/null && \
+		printf "<td align=\"center\" bgcolor=\"green\" > %s </td></tr>\n" "passed" >> ${LOG} || \
+		printf "<td align=\"center\" bgcolor=\"red\" > %s </td></tr>\n" "failed" >> ${LOG} ;
 	@printf "</table>\n" >> ${LOG}
 
 
