add testcases from JIRA
    PCC-251, PCC-255 & PCC-256

diff --git a/pcc-tests/regress/jira/Makefile b/pcc-tests/regress/jira/Makefile
--- a/pcc-tests/regress/jira/Makefile
+++ b/pcc-tests/regress/jira/Makefile
@@ -22,17 +22,19 @@ REGRESS_TARGETS =	PCC-21 PCC-23 PCC-33 PCC-45 PCC-47 \
 			PCC-224 PCC-225 PCC-226 PCC-227 PCC-228 PCC-232 \
 			PCC-234 PCC-236 PCC-237 PCC-238 PCC-239 PCC-240 \
 			PCC-241 PCC-242 PCC-243 PCC-244 PCC-245 PCC-247 \
-			PCC-248 \
+			PCC-248 PCC-251 \
 			PCC-376 PCC-377 PCC-378 \
 			PCC-380 PCC-382 PCC-383 PCC-385 \
 			PCC-460 PCC-461 PCC-462 PCC-464 \
 			PCC-476 PCC-476-1 PCC-477
 
-REGRESS_O2_TARGETS =	PCC-177 PCC-178 PCC-184 PCC-194 PCC-250
+REGRESS_O2_TARGETS =	PCC-177 PCC-178 PCC-184 PCC-194 PCC-250 PCC-256
 
 REGRESS_PIC_TARGETS =	PCC-186 PCC-249
 
 REGRESS_E_C_TARGETS =	PCC-211
+
+REGRESS_E_CC_TARGETS =	PCC-255
 
 REGRESS_TARGETS_FAIL =	PCC-161 PCC-221
 
@@ -66,6 +68,12 @@ test:
 	do \
 		printf  "   %-20s \t\t " "$$TARGET" ;\
 		${CC} ${CFLAGS} -o $$TARGET.out -E -C $$TARGET.c 2>/dev/null 1>&2 && \
+			echo "passed" || echo "failed" ;\
+	done 
+	@for TARGET in ${REGRESS_E_CC_TARGETS} ;\
+	do \
+		printf  "   %-20s \t\t " "$$TARGET" ;\
+		${CC} ${CFLAGS} -o $$TARGET.out -E -Wp,-CC $$TARGET.c 2>/dev/null 1>&2 && \
 			echo "passed" || echo "failed" ;\
 	done 
 	@for TARGET in ${REGRESS_TARGETS_FAIL} ;\
